name: lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, bing/ci-udeps]

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt

      - name: cargo fmt
        run: cargo +nightly fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install rust toolchain
        run: rustup toolchain install nightly-2024-06-10

      - name: Install Clippy
        run: rustup component add --toolchain nightly-2024-06-10 clippy
      
      - name: cargo clippy
        run: cargo clippy --all

  udeps:
    name: udeps
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: install rust toolchain
        run: rustup toolchain install nightly-2024-06-10

      - name: install cargo binstall
        run: cargo install cargo-binstall

      - name: install udeps
        run: cargo binstall cargo-udeps

      - name: cargo udeps
        run: cargo udeps
